### ISSUE TITLE
As a global admin, I want a one-time import of data from lending card XML files so that I can manage borrowing events and borrowed items in the database.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#75] opened 2018-04-03 15:09 UTC
## Notes for testing
- [x] borrowing events from xml cards should be associated with the corresponding account and person by mep id; pick an xml file or two to compare/sanity check
- [x] dates with years in the 1900s should be marked as year unknown and display in --MM-DD format (still browsable by 1900 in the date hierarchy at the top of the borrow admin page)
- [x] partial dates have been imported and marked for what date information is certain (e.g. YYYY-MM or YYYY)
- [x] notes in the xml should be preserved in borrow event notes
- [x] cardholders who did not have an account before should have one now (e.g. aldington)
- [x] purchased/returned item status should be set based on keyword terms provided (BB, bought, return)
- [x] items with missing mep id or no mep id should have a new item title created
- [x] unclear titles should have a new item record created; `<unclear/>` tag should be rendered as `[unclear]` in the title
- [ ] all text marked within `<del>` tags within a borrowing event should be added db borrow notes field
- [x] any dates in a borrowing event not marked as `checkedOut` or `returned` should be added to notes
- [x] xml files that document borrowing events for multiple cardholders should be split out based on the person id of the name in the head of the card (check e.g. bernheim and other known multiple cases)
- [x] bibliographic details should be added to item and borrow notes: author, publisher, date added to item record; `biblScope` and edition added to borrow notes
- [x] borrowing events works for organizations also (check e.g. synops, mesure); Note that organizations are _not_ automatically flagged as orgs by import, but it's a small number and can be done after import
- [ ] borrowing events with `notBefore` and `notAfter` dates are imported; partial date should be set based on overlap in the before/after dates (e.g. if month and year are the same, or month and day but different years, where year was unknown); full notbefore/notafter text added to the borrow event notes
- [ ] borrowing events associated with generic ids should _not_ be aggregated by mep id (see list below https://github.com/Princeton-CDH/mep-django/issues/75#issuecomment-386423595); each generic mep id should have zero borrows; e.g. borrowing event associated with one of these should have an item stub record created with available bibliographic data from the borrowing event

## Notes for development
- [x] script should import all borrowing events from all card xml transcription files (still pending xml/data work)
- [x] borrowing events should be associated with account for cardholder identified by MEP id
- [x] handle partial dates
- [x] notes in xml should be preserved as notes in db record
- [x] if cardholder does not yet have an account, create it
- [x] set purchased flag based on BB / "bought" in notes
- [x] dates with year 1900 should be marked as year unknown
- [x] handle titles with missing MEP id or NO mep id
- [x] handle unclear titles: generate stub item for all titles; import any notes associated with borrowing event into the stub record
- [x] handle `<del>` tags - include ALL text marked within `<del>` tags within a borrowing event in a notes field, along with whatever tags (useful in the case of dates) surround the text and specify its significance.
- [x] add any dates inside a borrowing event not tagged as `checkedOut` or `returned` to notes
- [x] handle card files with multiple cardholders: key on first cardholder persName in the `<head>` for each card page
- [x] preserve bibliographic data in item notes (or borrowing event notes?)
- [x] handle organizations
- [x] handle `notBefore` / `notAfter` attributes on dates with no `when` attribute
- [x] add logic to ignore mep id grouping for known generic titles (final list TBD, but includes "Poems", "Collected Poems", "Plays", "Essays", "Three Plays")

**Comment by rlskoeser** [comment] 2018-04-10 21:50
Card import questions so far, in no particular order:

- Please provide documentation and/or examples about how purchases of borrowed items are encoded. I haven't been able to find any.
- How should I handle unclear or partially unclear titles?
- Some cards are for people with no accounts; should an account be automatically created?
  Examples: 
   - aldi.ri Richard Aldington
   - chur.ba Barbara Church
   -  coch.et Etienne Coche de la Fierté
- How to handle shared accounts; what about when the account does not already exist, or when one person has an account but other people do not?  Examples:
   - bernheim.tei.xml: three cardholders: bern.fr Françoise Bernheim, bern.an Antoinette Bernheim, prot.al Aline Prot; all three are in the personography, only bern.an is in the logbooks and has an account
   - le_moal.tei.xml: moal Mrs le Moal, moal.pa Mr Paul le Moal
- What should I do, if anything, with `<del>` tags, e.g. around `<bibl>` ?
- What should I do, if anything, with about biblscope ?
  `<biblScope unit="volume" from="1" to="2">2 vols</biblScope></bibl>`
- Should notes in the xml be preserved in borrowing event notes?
- There are borrowing events with title id not in the borrowed titles list. Any ideas how to handle? Examples:
  - groethuisen.tei.xml mep:005386
  - leyris.tei.xml Mep:?
  - mesures.tei.xml mep:00g90j
  - de_vigan.tei.xml mep:009n4b
- What do you want me to do with the 1900 dates?  Should I mark year as unknown?

**Comment by rlskoeser** [comment] 2018-04-10 21:54
I've made a few small corrections to the card XML files to support import, but I don't think anything was questionable: just some date formatting issues and typos, a missing title id, and an attribute on the wrong element.  You can review here https://github.com/Princeton-CDH/mapping-expatriate-paris/commit/d6de37270be1200747d0e5d914980f55e8945c70

**Comment by elspethgreen** [comment] 2018-04-11 01:46
I have some answers, but not all!

- Purchased items
(I've been trying to insert the code into Github to demonstrate, but it keeps treating it as code and not displaying it properly)
Take a look at the rodken.tei file.  Three of the four books have a check out date, but not a return date--instead, they have a note with "BB" included within the borrowingEvent tag.  BB is the typical notation, but there is also "bought," "bought book," and probably others.  The shared feature of all of the purchased item events, though, is that none of them will have a return date.
- This is a great question about the "unclear" tags.  @jkotin do you have ideas about this?
- Yes, accounts should be created for all people with cards.  These are people who are members, but are not mentioned in the logbooks we have (we are still missing some)
- I'm not sure the best way to handle the shared accounts--this is a case in which, perhaps, the "account" should simply be "Bernheim" and be affiliated with all three people?
- In general, the "del" tags are inserted to reflect a crossed out title in the cards; we didn't want to lose track of the potentially interesting information that a person had initially meant to borrow one book, then decided to borrow another.  My instinct (@jkotin what do you think?) is to move this information to notes.
- I'm not sure what we should do with biblscope.  We do want to keep the information contained therin, which is generally which (of potentially several) volumes a particular person borrowed, but I'm not sure how we would display that on the site.  Perhaps it should be migrated into a special kind of note, or modifier for the book borrowed?
- Notes inclued within the borrowingEvent tag should be included in the borrowingEvent.  If the note says "BB" or "bought book" or "bought," it should trigger tagging the event as a purchasing event.
- These titles probably just slipped through the net.  I was only able to find them by searching the mepID, though; they don't seem to be in the files you indicate (the Groethuisen title is actually in Hemingway, for example).  Not sure what's going on!
But generally, these should still generate a "book" stub.  The mepID is going to be pretty vestigial--something that we should be able to sort by, to group book stubs that were identified during the OpenRefine work as likely to be the same book, but which will become less and less important the more we physically merge those stub records.
- The 1900 dates should be marked as year unknown, but the month-and-day information preserved.

**Comment by jkotin** [comment] 2018-04-11 02:29
Let's discuss the following at our meeting tomorrow:

1. Unclear titles
2. Crossed out titles
3. Shared accounts

Are there other issues we should discuss?

Best,

J

**Comment by rlskoeser** [comment] 2018-04-19 18:49
Some new questions and updates.

@elspethgreen I absolutely did not give you the right filenames for the missing title ids.  I apologize, it was a dumb mistake on my part.  Here are more details:

## missing titles
* transcriptions/cards/h/hemingway.tei.xml: hemi.er Ernest Hemingway
  Failed to find item with MEP id mep:005386 - looks like this was entered as the wrong id
   from hemingway.tei.xml:
```
     <ab ana="#borrowingEvent">
          <date ana="#checkedOut" when="1925-12-10">〃 10</date>
          <bibl ana="#borrowedItem" corresp="mep:005386">
          <title>Budden Brooks</title> in 2 vols.</bibl>
          <date ana="#returned" when="1926-01-19">Jan 19</date>
        </ab>
```
from borrowed-titles:
```
  <row>
        <titleid>mep:00688t</titleid>
        <borrowerid>#hemi.er</borrowerid>
        <borrower_name>Ernest Hemingway</borrower_name>
        <title>Budden Brooks in 2 vols.</title>
        <regularized_title>Buddenbrooks</regularized_title>
    </row>
```
* transcriptions/cards/m/macliesh.tei.xml: macl.ar Archibald MacLeish
Failed to find item with MEP id Mep:?
Not in borrowed titles; I'll add logic to create a stub
* transcriptions/cards/m/michaelides.tei.xml: mich.l Madame L. Michaelides
Failed to find item with MEP id mep:00g90j
from the xml:
```
   <ab ana="#borrowingEvent">
                         <date ana="#checkedOut" when="1930-04-02"></date>
                         <bibl ana="#borrowedItem" corresp="mep:00g90j"><title>This once</title></bibl>
                         <note>, 0.50 </note>
                         <date ana="#returned" when="1930-04-05"></date>
                     </ab>
```
Not in borrowed titles; I'll auto-create a stub
* transcriptions/cards/r/reynal.tei.xml: reyn.je Jeanne Reynal
Failed to find item with MEP id 001p3c
this one is just missing the 'mep:' prefix, id looks right in borrowed-titles
```
<ab ana= "#borrowingEvent">
                 <date ana="#checkedOut" when="1931-05-07">  May 7  </date>
                 <bibl ana="#borrowedItem" corresp="001p3c">
                     <title>  Women in Love</title>
                 </bibl>
                 <date ana="#returned" when="1931-05-29">May 29.</date>
             </ab>
```
* transcriptions/cards/vw/de_vigan.tei.xml: viga.mo Mlle Monique de Vigan
Failed to find item with MEP id mep:009n4b
```<ab ana="#borrowingEvent">
      <date ana="#checkedOut" when="1947-09-07"/>
      <bibl ana="#borrowedItem" corresp="mep:009n4b">
        <author>Powys</author>
      </bibl>
      <date ana="#returned" when="1948-06"/>
    </ab>
```
Id is not in borrowed-titles.xml.  Not sure how to handle an item with no title but an author.  Is that right? Let me know if you have any suggestions.

## date questions

* I found one 1320 date that seems pretty clearly a typo for 1932; I've corrected this in the XML (the team had a laugh about a time-traveler borrowing a book)
  Account #23: Raphael  Invitation to the Waltz 1320-12-28  1932-12-30  

* There are some 1901 and 1902 dates, look like they are all in Gertrude Stein.  Are these perhaps successive unknown years?  My inclination is to mark all 1900/1901/1902 dates as year unknown (the year will be preserved in the database but marked as unknown).

## missing cardholders

Found a few cardholder ids that aren't finding matches in the personography
* Person not found for mazo - transcriptions/cards/m/mazon.tei.xml
 * Person not found for mesu - transcriptions/cards/m/mesures.tei.xml; this was an organization in personography xml, which we haven't handled yet
* Person not found for reno - transcriptions/cards/r/renoir.tei.xml
* Person not found for ulma.d - transcriptions/cards/u/ulmann_d.tei.xml; looks to me like this is a typo of ulma.de.  If you can confirm, I'll fix.

Given the small number, I'm wondering about having someone manually create the person records (if they are indeed missing and not typos I didn't find) rather than coding logic to generate them from the script.

**Comment by rlskoeser** [comment] 2018-04-19 21:07
Here's the output from a preliminary import run on the test site.  The skipped files are related to questions we haven't answered yet -- shared accounts and cardholders not being found.

```
Account not found for bern.fr Françoise Bernheim, bern.an Antoinette Bernheim, prot.al Aline Prot
/home/deploy/mapping-expatriate-paris/transcriptions/cards/b/bernheim.tei.xml
Account not found for deni.el Madame Maurice Denis, deni.pi Monsieur Pierre Denis
/home/deploy/mapping-expatriate-paris/transcriptions/cards/d/denis.tei.xml
Account not found for denn.ho Mrs Frederic Dennis, denn.ma Mrs. A. L. P. Dennis (Mary Cable Dennis)
/home/deploy/mapping-expatriate-paris/transcriptions/cards/d/dennis.tei.xml
Failed to find item with MEP id mep:005386
Account not found for laug.ja James Laughlin, laug.le Leslie Laughlin
/home/deploy/mapping-expatriate-paris/transcriptions/cards/l/laughlin.tei.xml
Account not found for gall.ir Irma le Gallienne, gall.ri Richard le Gallienne
/home/deploy/mapping-expatriate-paris/transcriptions/cards/l/le_gallienne.tei.xml
Account not found for moal Mrs le Moal, moal.pa Mr Paul le Moal
/home/deploy/mapping-expatriate-paris/transcriptions/cards/l/le_moal.tei.xml
Account not found for leyr.pi Pierre Leyris, leyr.be Betty Leyris
/home/deploy/mapping-expatriate-paris/transcriptions/cards/l/leyris.tei.xml
Person not found for mesu
/home/deploy/mapping-expatriate-paris/transcriptions/cards/m/mesures.tei.xml
Failed to find item with MEP id mep:00g90j
Failed to find item with MEP id Mep:?
Person not found for mazo
/home/deploy/mapping-expatriate-paris/transcriptions/cards/m/mazon.tei.xml
Failed to find item with MEP id 001p3c
Person not found for reno
/home/deploy/mapping-expatriate-paris/transcriptions/cards/r/renoir.tei.xml
Person not found for ulma.d
/home/deploy/mapping-expatriate-paris/transcriptions/cards/u/ulmann_d.tei.xml
Failed to find item with MEP id mep:009n4b

Summary:
564 files processed
570 card holders
536 accounts found; 17 accounts created
20,187 borrowing events found in XML
19,020 borrowing events created
11 files skipped
```

**Comment by rlskoeser** [comment] 2018-04-27 20:46
Basic card import logic is now complete, except for the footnote functionality which we're tracking in #93 (in progress but not yet ready for testing).  Ran a test import on the latest xml starting from a fresh copy of production data.  Here's the script output:

```
python manage.py import_cards  ~/mapping-expatriate-paris/transcriptions/cards/
Person not found for moal
/home/deploy/mapping-expatriate-paris/transcriptions/cards/l/le_moal.tei.xml
No MEP id for cardholder Librairie des Deux Lycée - /home/deploy/mapping-expatriate-paris/transcriptions/cards/l/libraries_des_deux_lyee.tei.xml
Person not found for mesu
/home/deploy/mapping-expatriate-paris/transcriptions/cards/m/mesures.tei.xml
Person not found for mazo
/home/deploy/mapping-expatriate-paris/transcriptions/cards/m/mazon.tei.xml
No MEP id for cardholder  - /home/deploy/mapping-expatriate-paris/transcriptions/cards/m/mcnair.tei.xml
Multiple accounts found for roye
/home/deploy/mapping-expatriate-paris/transcriptions/cards/r/royer_sement.tei.xml
Person not found for reno
/home/deploy/mapping-expatriate-paris/transcriptions/cards/r/renoir.tei.xml
No MEP id for cardholder Les Revues - /home/deploy/mapping-expatriate-paris/transcriptions/cards/r/revues.tei.xml
No MEP id for cardholder Rhein-Verlag - /home/deploy/mapping-expatriate-paris/transcriptions/cards/r/rhein.tei.xml
Multiple accounts found for rich
/home/deploy/mapping-expatriate-paris/transcriptions/cards/r/richards_orpen.tei.xml
Multiple accounts found for rich
/home/deploy/mapping-expatriate-paris/transcriptions/cards/r/richardson.tei.xml
Person not found for ulma.d
/home/deploy/mapping-expatriate-paris/transcriptions/cards/u/ulmann_d.tei.xml

Summary:
564 files processed
568 card holders
542 accounts found; 18 accounts created
20,165 borrowing events found in XML
19,892 borrowing events created
11 files skipped
```

**Comment by rlskoeser** [comment] 2018-05-03 21:17
Successfully ran a full import on the test site with fresh data from production and latest xml!  Script summary output:
```Summary:
564 files processed
573 card holders
549 accounts found; 24 accounts created
20,165 borrowing events found in XML
20,165 borrowing events created
0 files skipped```

**Comment by elspethgreen** [comment] 2018-05-07 14:55
Aldington has an account now (and one that is flagged with a "has card") but it doesn't seem like any of his borrowing events are actually imported.  Looking at the TEI, I think this is because this file was an early Cliff experiment and is encoded somewhat differently.  The items are actually not encased within borrowing-event tags, but arranged in some kind of array.  I can add this to my list of small manual data cleanup.

Barbara Church looks good, so I think the import is basically running smoothly for the no-account card people.

**Comment by elspethgreen** [comment] 2018-05-09 00:11
@rlskoeser I found a potential problem--I spot-checked a deletion within a borrowing event and it was not represented in the database.  Here's the XML:
<ab ana="#borrowingEvent">
                    <date ana="#checkedOut" when="1938-10-28">Oct 28</date>
                    <bibl ana="#borrowedItem" corresp="mep:000488"><title><del>Those Barren</del> Joyful Delaneys</title></bibl> 
                    <date ana="#returned" when="1938-11-07">Nov 7</date>
                </ab>

Could it be because the title tag includes both the deletion and the actual title?  Could we adjust for this--it's probably something that happened more than once?

**Comment by elspethgreen** [comment] 2018-05-09 00:14
biblScope looks well represented in the notes for the borrowing events--but this structure is eventually changing based on our conversation with Regine, right?

**Comment by elspethgreen** [comment] 2018-05-09 00:30
The disambiguated titles look good--but I meant my list to be in addition to the ones that you'd already identified!  So definitely add these back to the list: “Poems”, “Collected Poems”, “Plays”, “Essays”, “Three Plays”

Also, I'm not sure I understand the note about the generic IDs being associated with zero borrows.  When I look at "Theatre," for example, each instance of "Theatre" has one borrow (which seems to make sense).  Is the ID with zero borrows a back-end thing?

**Comment by rlskoeser** [comment] 2018-05-09 13:59
@elspethgreen thanks for the feedback. Responses:

>  a potential problem--I spot-checked a deletion within a borrowing event and it was not represented in the database ...

How would you like to see this represented?  I am currently only looking for `<del>` directly under the borrowing event, but I could expand that to find them anywhere under the event - would that be sufficient?  i.e., in this case you would only see the del and not that it was inside a title.

> biblScope looks well represented in the notes for the borrowing events--but this structure is eventually changing based on our conversation with Regine, right?

Correct - the `biblScope` data in the notes is a provisional measure to give us access to the information in the database.  It will need to be moved into structured fields eventually.

> Checking out the notBefore notAfter's has revealed an encoding problem rather than an import problem. An overzealous encoder has recorded entirely un-listed return dates (in some cases, expressly marked as "returned") as "notBefore" the listed check-out date.

I noticed that too!  However, I think the current import logic is working properly: the date is marked as completely unknown because there is no overlap between `notBefore` and `notAfter` dates (since there is no `notAfter`), and I'm only adding the text of the dates to the notes when I have both.  Do you have any concerns with how this one looks as currently imported on the test site?

> The disambiguated titles look good--but I meant my list to be in addition to the ones that you'd already identified! So definitely add these back to the list: “Poems”, “Collected Poems”, “Plays”, “Essays”, “Three Plays”

Ah, sorry about that!  I wasn't paying attention to the fact that they weren't in your list; I'll add them to my list.

> I'm not sure I understand the note about the generic IDs being associated with zero borrows.

If you search for the original generic entries by mep id, e.g. `mep:00060b` for Theatre, you'll see what I mean.  The stub records created by importing the borrowed titles for these ids are now skipped, because we don't want to aggregate borrowing events for them.  I don't think it's a big deal, just wanted to make sure you're aware.  Should be easy enough to remove this after the import runs and we're comfortable that we don't need them anymore.

**Comment by elspethgreen** [comment] 2018-05-09 22:29
I think it would be good to have a "del" anywhere within the borrowing event represented--that would take care of the example I found, and probably others I haven't yet dreamt of.  

So that's an import change, but everything else (+ expanding the list of non-collapsed titles) should be good.  The strange unpaired nofAfter's are represented absolutely correctly--it just freaked me out to see the TEI mistake.

**Comment by rlskoeser** [comment] 2018-05-11 20:11
Updated the test site with a fresh copy of production data and ran the import on the latest xml.  Import now looks for `<del>` tags anywhere in the borrow event (not just directly under); image paths in footnotes now use the full url.

Import script output:
```
Summary:
564 files processed
574 card holders
550 accounts found; 24 accounts created
20,165 borrowing events found in XML
20,165 borrowing events created
0 files skipped
```

**Comment by elspethgreen** [comment] 2018-05-14 00:39
I think we'll have to make another minor change to the image URL--it seems like trying to get to a specific image (rather than just the whole file) is making the link fail.  But the information regarding the specific image is super useful for finding the right borrowing event quickly.  Could we remove the specific image path (taking this, https://diglib.princeton.edu/tools/ib/pudl0123/825298/b/boulenger_bidoire/00000003.jp2 and making it this https://diglib.princeton.edu/tools/ib/pudl0123/825298/b/boulenger_bidoire/) but reproduce the image path in the associated "Notes" field of the footnotes?

**Closed** 2018-05-14 17:40 UTC
