### ISSUE TITLE
Indexing Issue

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#683] opened 2020-07-19 16:09 UTC
Some items are still not showing events after they have been updates. See link and screen shots.

https://shakespeareandco.princeton.edu/books/?query=&circulation_dates_0=&circulation_dates_1=&sort=circulation&page=61

<img width="865" alt="Screen Shot 2020-07-19 at 12 04 22 PM" src="https://user-images.githubusercontent.com/12616674/87879424-b53c1300-c9b8-11ea-8edc-932408dae732.png">

<img width="865" alt="Screen Shot 2020-07-19 at 12 08 55 PM" src="https://user-images.githubusercontent.com/12616674/87879428-bbca8a80-c9b8-11ea-9275-57ca2fe0ac2c.png">

**Comment by jkotin** [comment] 2020-07-19 16:11
Re-saving the item fixes the problem. I'm happy to close, but will leave open until I receive confirmation.

**Comment by rlskoeser** [comment] 2020-07-20 13:24
@jkotin I should have done a full reindex when I deployed the last update, but I didn't think of it. Any idea if the things that are out of date are from before that release went out, or if the logic for indexing books when associated events change is not working properly?

**Comment by jkotin** [comment] 2020-07-20 13:26
The three events w/ problems were new books I added on July 11, in the evening.

**Comment by jkotin** [comment] 2020-07-20 13:32
I think there's still an issue with indexing. I just fixed a mistake for "How to Teach a Foreign Language." The search page shows 5 events. The book page (which is correct) shows 4.

**Comment by rlskoeser** [comment] 2020-07-29 21:08
Duplicate of #667 (which was re-opened)

**Closed by rlskoeser** 2020-07-29 21:08 UTC
Labels: bug
