### ISSUE TITLE
Standardize subscription lengths

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#45] opened 2017-10-11 21:11 UTC
Many subscriptions listed under "Subscribe" (https://test-mep.cdh.princeton.edu/admin/accounts/subscribe/) have start and end dates that do not correspond to the duration of the subscription.  After consulting with Josh, I have learned that the logbooks only have start dates, so the end date must always be extrapolated from the duration.  This must be what is happening here--but, in many cases, the end date looks off.  What's going on?

**Comment by bwhicks** [comment] 2017-10-11 21:28
@elspethgreen I think what you must be seeing is the way I'm tallying months right now, i.e. `3 months = 4 * 7`.

I don't know the Beach records well enough to say, but she might be thinking like that, or she might be thinking as in 'a month is equal to the same day next month'. It's also possible I have a blooper in the code.

Do you know how precise she was in that metric (i.e. month = 4, 7 day weeks vs month = from mm/dd to mm+1/dd)? It would inform the import script to be sure.

**Comment by elspethgreen** [comment] 2017-10-11 22:11
I talked to Josh this afternoon, and while we don't know exactly what her methods were, it seems far more likely that a 1 month of subscription from October 10 would be up on November 10, just for simplicity's sake (also, only February is actually 28 days).  So that's what we would prefer on the import!

**Comment by jkotin** [comment] 2017-10-12 00:43
Yes, one month is one calendar month: so a six-month subscription that starts on 11/4 ends on 5/4 the next calendar year.  See card attached below as an example. -- J

[cid:6C032005-FA73-4A7F-A311-16D1F1898DD6@hsd1.nj.comcast.net.]



---------------------------
Joshua Kotin, Associate Professor
Princeton University

press.princeton.edu/titles/11207.html<http://press.princeton.edu/titles/11207.html>








On Oct 11, 2017, at 6:11 PM, elspethgreen <notifications@github.com<mailto:notifications@github.com>> wrote:

I talked to Josh this afternoon, and while we don't know exactly what her methods were, it seems far more likely that a 1 month of subscription from October 10 would be up on November 10, just for simplicity's sake (also, only February is actually 28 days). So that's what we would prefer on the import!

**Comment by rlskoeser** [comment] 2017-10-12 13:39
Adding card image for documentation purposes:

![mme andri de la forest-divonne membership card](https://user-images.githubusercontent.com/691231/31498866-1d777112-af31-11e7-8747-3c4cc34074a0.png)

**Comment by bwhicks** [comment] 2017-10-12 13:40
Thanks @rlskoeser.

**Comment by bwhicks** [comment] 2017-10-12 13:46
I'm closing this as a duplicate of tasks in #36 and will link it there as well.

**Closed by bwhicks** 2017-10-12 13:46 UTC
