### ISSUE TITLE
Revise design of "Bibliography" page for Books to reflect the added information

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#319] opened 2019-05-16 19:45 UTC
in light of the new information provided by the OCLC reconciliation, we potentially have a lot of content that could be displayed on book detail pages! this includes:

- separate headings for different types of creators (already included in some designs, but not sure if we're going for it)
- work vs edition level metadata
   - should have a list of known issues (issue number and date) and volumes (volume number)
- a link to view the item in OCLC
- subject and genre information
- should have a space for public notes (optional)
- should have a space for problem icon for works flagged as problem/generic

**Comment by gissoo** [comment] 2020-02-04 16:53
+ Issue and volume information to be added

**Comment by gissoo** [comment] 2020-02-17 21:38
@clmahoney @jkotin Would you please provide me with some examples? I'm designing now and trying to cover multiple variations. It would be helpful to have useful examples.

**Comment by jkotin** [comment] 2020-02-18 01:12
@clmahoney should supply examples of books and periodicals. Please select examples with one creator and many creators (of different types). Also pick at least one short title and one long one. Some multivolume works have different volume subtitles—that would be helpful too.

**Comment by clmahoney** [comment] 2020-02-18 18:56
@jkotin @gissoo I'll get these to you by the end of today. One question I have for both of you: should I be writing volumes in roman numerals, or just numbers?

**Comment by gissoo** [comment] 2020-02-18 19:02
@clmahoney thank you! Design-wise, either one should work, 
development-wise I'm not sure, @rlskoeser do you have any concerns with this?

**Comment by rlskoeser** [comment] 2020-02-18 19:08
I think the volume number question is a decision for @jkotin to make. My understanding of the adjustments we proposed to the edition model is that we would only use the date field for sorting — the other fields would be largely for display. However, we haven't finalized the decisions on the edition model changes; see #518. 

We will need to know how issues and volumes should display _and_ how to generate that display from the fields in the database.

**Comment by clmahoney** [comment] 2020-02-18 19:13
- Multivolume work example: 7537, "A Hazard of New Fortunes" - one borrow (the Stein) is for 2 vols, while the other two borrows (Bertha Edel) is vol 1 and then vol 2. 

- Multivolume work example with different subtitles: 1712, "Studies in the Psychology of Sex"

**Comment by clmahoney** [comment] 2020-02-18 19:18
- Multivolume work with multiple authors example: 1654, "The Love Letters of Thomas Carlyle and Jane Welsh"

**Comment by clmahoney** [comment] 2020-02-18 19:22
- Multivolume work with long title example: 673, "The Mediaeval Mind: A History of the Development of Thought and Emotion in the Middle Ages"
--> just a note: that spelling is correct

**Comment by clmahoney** [comment] 2020-02-18 19:25
- Periodical example: 4598, "The Dial"

**Comment by clmahoney** [comment] 2020-02-18 19:26
- Work with multiple editions example: 4094, "Religio Medici"

**Comment by clmahoney** [comment] 2020-02-18 19:27
- Periodical example: 5683, "transition"

**Comment by jkotin** [comment] 2020-02-18 19:44
Let's use arabic numerals, not roman.

**Comment by gissoo** [comment] 2020-02-20 20:51
@jkotin I have uploaded 4 of the 7 examples that Cate provided (in desktop only for now). 
These 3 screens entail all the questions that need to be solved before I move forward.
You can view them here: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e4ef09016f49f69dece6c62)

Here are some points:
1. Looking at all the varieties that exist with volume and issue information I decided to lay out the information together (not in separate fields) to allow more flexibility and better readability, especially in the case of periodicals. What would you call this field? I strongly recommend we don't use the term "Edition" in the label of this field as this field is not always communicating exactly the "edition" information, and it will be confusing. I did some research but I can't find anything yet that's clear and exact/correct enough for our purpose here. 

2. Please look at the "problem" icon I created, or as I would like to refer to it as "uncertainty" icon on the screen on the left. Let me know what you think. I am trying to avoid an exclamation mark which communicates "danger" more often and doesn't quite allow for grey areas such as "uncertainty". 

3. For periodicals, I would strongly suggest we do not display the author field at all, and instead start with the publication date on the top left as you can see on the middle and right screens. 

4. Also, after speaking with RSK, we recommend to not display "Editor", "Translator", and "Publisher" information when any of them do not exist regardless of the reason that they do not exist. 

Please take a look at the volume and issue information on the three screens, and let me know what you think. 

Also, @clmahoney: What is the transition 19-20 under “Edition Transition 19-20 (1930) no. 19” in 5683? Is “Transition 19-20” one of the title variants?

**Comment by jkotin** [comment] 2020-02-21 00:59
Thank you Gissoo!  To answer your questions:

1. Could we have two different titles for the field, one for periodicals ("Issue" or "number") and one for multivolume works ("volume")?  If having two different titles is impossible, then "volume" works best.

2. I love the problem/uncertainly icon!

3 & 4. These seem similar to be similar questions. Can only populated fields show up?  So "editor" only shows up if an editor is indicated in the database? Likewise, date, author, publisher, etc.?

I'll respond to the designs in a separate note.

**Comment by jkotin** [comment] 2020-02-21 01:31
Notes on designs:

1. I think there should be an explicit "author" and "date of publication" field. As it stands, e.g., it is unclear that Havelock Ellis is the author and 1897 is the date of publication.

2. On the Ellis page, I'm wondering about the spacing for the individual volumes. There seems to be more space between vol. 1 and vol. 2 than between vol. 2 and vol. 3.  I also wonder about having a hanging indent or a way to separate the volume from title, especially if the title is long.

3. Re: dates -- I think it would be better to have date ranges, not discrete dates, so: "1920–1921" or "1920–1923, 1925, 1928–1932."  Both multivolumes and periodicals might have date ranges. 

4. For the actual volume numbers of periodicals, we're going to try to make them as consistent and simple as possible.  It will most likely be volume, number, month/season, year, so, e.g.: "Vol. 1, no. 2, March 1923." I am open to discussing different ways of presenting this information.

5. Re: the reference field -- where will the OCLC link go?  (I want to be sure it's to the public/free OCLC record.)  Would you send me a sample? I am wondering whether some users might be confused and expect to get a Wikipedia page, such as https://en.wikipedia.org/wiki/The_Dial#Modernist_literary_magazine for The Dial. Is it possible to have multiple references?

6. We are hoping to have links to full text versions. That should be part of the design.

7.  Will users be able to see the activity for a particular volume or issue? if so, how will that work?  Or will a user have to go to activity for the whole book/periodical and order the activity by issue and/or volume?

**Comment by rlskoeser** [comment] 2020-02-21 16:10
A few comments on some of these questions from my perspective.
- I'm ok with having a different label for "editions" (issues) associated with periodicals because that can be based on item format. I don't know that we have a way to identify multivolume works from others (although maybe we don't need to since only periodicals and multivolume works are in scope for now).
- Where would the multiple years or date ranges come from? Our work model only has year. Would it need to be aggregated from the edition records, and will that make sense in all cases?
- We don't plan to have a separate activity list for particular volumes or issues; issue/volume information will be included in the book activity list. Seems plausible to me that we should make it sortable so you can look at activity for a specific issue or volume in one place.

**Comment by jkotin** [comment] 2020-02-21 16:29
Re: dates -- the dates would have to come from the issue/vol information: yes, aggregated edition records.  I think that would work in all cases.  (I can't think of exceptions.) All periodicals and many multivolume works will have date ranges (just years).

Less ideal solutions (although acceptable):  a/ don't include dates for items with date ranges, b/ allow date ranges in the date of publication field in database.

**Comment by gissoo** [comment] 2020-02-24 17:54
@jkotin I'll answer your questions shortly with the revised designs I have, but @rlskoeser said she can answer your question #5 better.

**Comment by rlskoeser** [comment] 2020-02-24 18:27
@jkotin in response to your question:
> Re: the reference field -- where will the OCLC link go? (I want to be sure it's to the public/free OCLC record.) Would you send me a sample? I am wondering whether some users might be confused and expect to get a Wikipedia page, such as https://en.wikipedia.org/wiki/The_Dial#Modernist_literary_magazine for The Dial. Is it possible to have multiple references?

We can use the `edition URI` on the Work record for the OCLC link; e.g. http://www.worldcat.org/oclc/606022651 resolves to page https://www.worldcat.org/title/brass-check-a-study-of-american-journalism/oclc/606022651 

I don't know if that will cause confusion, since it might not always be the specific edition. But the work URIs don't give a very user-friendly response, so I don't recommend using them. 

Currently the model doesn't allow for multiple references. On the work record we have work URI, edition URI, and ebook url.

**Comment by gissoo** [comment] 2020-02-24 19:09
@jkotin 
To answer your first comment's questions:
1. I have created separate titles for books vs. periodicals. I have named them "Volume" for multivolume words, and "Number" for periodicals. I'm following the format you have provided in your second comment: "Vol. 1, no. 2, March 1923." – therefore I would say let's be consistent and use the same set/circle of terms for this (I'm avoiding "issue" or "edition" in this case) 
@jkotin there is a periodical in my example that is multivolume, you're also thinking of "volume" as a label for this periodical, correct? 

2. Great! I will upload the icon! 

3 and 4. You're correct for all of them except for "publication date". 
"editor" only shows up if an editor is listed in the database, same for author, and publisher. 
My logic is that there will always be a "publication date" for any work, so when we don't have it, I suggest we display "uknown". @jkotin @rlskoeser what do you think? I would suggest to actually do the same for "publisher" since logically any work has had to have a "publisher", is that correct? Is this doable, code/database-wise?

**Comment by gissoo** [comment] 2020-02-24 19:48
@jkotin 

1. I agree with you and have created explicit "author" and "date of publication" fields.

2. The spacing on the Ellis page was my mistake. I do not recommend an indentation, however I have revised it now to make it easier to read, so let me know what you think.

3. I agree with you on the date ranges. I have revised the designs.

4. I like this example and its order: "Vol. 1, no. 2, March 1923.", I thought about using "no." too. I have revised the designs to reflect this.  

5. RSK answered – can share my opinion if/after @jkotin responds. 

6. I have revised the design to reflect a link to the "full text" version. 

7. Regarding seeing the activity for a particular volume or issue, the user has to go to activity page (or "Circulation" tab, as we decided to call it). I agree with @rlskoeser. @rlskoeser are we adding "volume" and "issue" as two additional columns under the "circulation" tab to make them sortable?

**Comment by jkotin** [comment] 2020-02-24 21:37
The numbers are no longer lining up, NB:

1. I don't think we should include the OCLC link on the site. It should only be available for the data export. (The OCLC page is too confusing and I don't like linking to random editions.) I do think we should have space for a link to a full text or epub edition. I'm neutral about whether we have a Wikipedia link.

2. I do not want to display "unknown" when we do not know a publisher.  Most publishers will be unknown.  And even if known, we won't have the info in the database.

3. I'm OK with publication date always showing up, if we have date ranges.

4. The last issue is about labels: issue, volume. I'm going to write a separate note about that.  Let me know if I've missed anything else!

**Comment by jkotin** [comment] 2020-02-24 21:40
@gissoo @rlskoeser I'm starting to think now that we might just want to have one label for editions: "volume."  Having two different labels -- "volume" and "issue" -- might confuse as much as clarify. Do you have an opinion here?  What is the periodical with multivolumes than you mention, Gissoo?

**Comment by rlskoeser** [comment] 2020-02-24 21:41
@jkotin one label is easier to implement. I can see how different labels might lead to confusion, and would be nice to have the data export terminology match the public site.

**Comment by gissoo** [comment] 2020-02-24 21:52
@jkotin here are the designs: 
Mobile: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e54452cba44e3671637f02e)

Tablet: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e54452c4bd744669415df43)

Desktop: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e54452c27cd32677b179a54)

**Comment by gissoo** [comment] 2020-02-24 21:54
@jkotin @rlskoeser I will share my opinions tomorrow and will revise designs further tomorrow based on your latest comments. I have to run for a phone meeting in five minutes.

**Comment by gissoo** [comment] 2020-02-25 13:49
@jkotin @rlskoeser I agree with you on the labels because you initially said "multivolume" works vs. "periodicals". And "The Dial" (4598 in the database) is a multivolume periodical, so I suspect this creates problems with implementation. 

However, I would strongly encourage you to not call the label "Volume", or "Issue", (or "Edition" as discussed before), because that field could include both of the first two terms or one of them. It's just not good to call it "Volume" when there is no "volume" in one case or "issue" when there is only volume information. Can you think of any other terms?

**Comment by gissoo** [comment] 2020-02-25 14:16
@jkotin  just following up on two points: 
>     2. I do not want to display "unknown" when we do not know a publisher.  Most publishers will be unknown.  And even if known, we won't have the info in the database.
> 
So what is the value of having this field at all at this point? (By "Unknown" I mean it's unknown because we don't have them in the database – or really, we are unsure of its existence at all)

>     3. I'm OK with publication date always showing up, if we have date ranges.
> 
Do you mean that you won't be ok with publication dates showing if we don't have date ranges?

**Comment by jkotin** [comment] 2020-02-25 17:30
@gissoo responding to your notes today:

1. How about "Volume/Issue" as a label?  Or "Volume/Number"?  The Dial, btw, is a regular periodical.  Many periodicals use a volume and issue number system. The volume number usually indicates a year.  E.g. a quarterly journal will have four numbers in each volume.

2. I agree about publisher: no need to include it.  We can note the publisher in the public notes if important.

3. If we don't have date ranges, we won't be able to present dates for some periodicals. Accordingly, if date is always going to be present, we'll need to show ranges.

**Comment by jkotin** [comment] 2020-02-25 17:30
@gissoo responding to your notes today:

1. How about "Volume/Issue" as a label?  Or "Volume/Number"?  The Dial, btw, is a regular periodical.  Many periodicals use a volume and issue number system. The volume number usually indicates a year.  E.g. a quarterly journal will have four numbers in each volume.

2. I agree about publisher: no need to include it.  We can note the publisher in the public notes if important.

3. If we don't have date ranges, we won't be able to present dates for some periodicals. Accordingly, if date is always going to be present, we'll need to show ranges.

**Comment by rlskoeser** [comment] 2020-02-25 17:39
Would something like Copy/Copies make sense as a label for edition/issue/volume?

**Comment by gissoo** [comment] 2020-02-25 18:43
@jkotin Great, I prefer "volume/issue" better than anything else at this point.

**Comment by gissoo** [comment] 2020-02-25 21:35
@jkotin @rlskoeser Here are the latest revisions to these pages: 

Mobile: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e55912005203463186fb3cd)
Tablet: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e5592deba44e367163f104c)
Desktop: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e55912088e36273d220c4f1)

**Comment by jkotin** [comment] 2020-02-26 00:49
Notes:

1. I love the uncertainly icon. But I'm not 100% sure it's necessary. Can the public notes serve to explain if/why we can't identify a book?  The lack of information for problem books will also be an indicator.  Let me know what you think.  As I said, I love the icon and would like to keep it if it's useful.

2. On mobile for "transition" -- the last entry in volume/issue is "Transition 19-20." Is that a mistake?  I don't think it's a design issue, but I'm mentioning just in case.  Also: "transition" should be lowercase throughout -- it's an idiosyncrasy of that particular journal.

3. Will "Full-text" be a link or appear as the words "Full-Text"?  Can we have options there?  E.g. PDF or .epub? Also, for periodicals, we won't be able to link to the full text of each issue. Instead, we would provide links such as: https://modjourn.org/journal/blast/ [for Blast] or https://bluemountain.princeton.edu/exist/apps/bluemountain/title.html?titleURN=bmtnaap [for Broom].

4. Should the subtitles of the book volumes be italicized?  They would be italicized in a bibliography.  Might be a nice way to differentiate from volume number.

5. Should the titles of books be all caps at the top of the page?  Or in title case, following the example of the members?  Should we have "Shakespeare and Company Project" underneath the title?

6. Publication Date should either be above author/editor/translator or below.  Not in the middle of creators.

7. On the desktop designs, you added "display only if exists."  That applies to tablet and mobile too, correct?

8. Illustrator (etc) will display too, if the information is present.

**Comment by rlskoeser** [comment] 2020-02-26 15:23
Some comments after looking at the designs and seeing Josh's comments and questions.

1. The desktop design makes it look like we have potentially two sets of notes, but we only have one public notes field. My understanding is that we'll know if a record has some 'uncertainty' based on keywords in the private notes field (e.g., PROBLEM and GENERIC). What do you think about displaying the uncertainty icon _instead_ of the info icon for the public notes? (The notes still provide information, but presumably they will be clarifying the nature of the uncertainty)
2. From what I recall "transition 19-20" is an idiosyncrasy of the journal (one of the ones forcing us to revise the volume field in the edition record). 
3. I don't think "Reference" makes sense as a heading for full text, and it sounds like "full text" isn't the best label. What about "Read online" ? In the backend, this is just a URL so you can put whatever link you want. If you plan to link directly to a PDF or EPUB we should warn people somehow. I recommend linking to an html page that provides access to other formats whenever possible.
4. Italicizing might be nice for titles. I don't think we need both a comma and a line break after the line number. If we italicize do we still need the line break?
5. I like the idea of making the book titles proper case the way we did with members.
6. Are we differentiating (or should we) original publication date (i.e. for the work) with actual publication dates, e.g. in the case of volumes/issues?
7. Yes, anything not displayed on desktop will not be shown on tablet or mobile.
8. What about other creators? Josh, you mentioned that we have "introduction" and "preface" as other creator types. How will we know how to order creators on the page?

**Comment by jkotin** [comment] 2020-02-26 16:20
Responding by the numbers:

1. I think we'll have some public notes that do not involve uncertainty. E.g., we might use the public notes to indicate that item was bought for a specific person or to indicate when an item is not a book or periodical.  (E.g., some photographs appear on the cards -- among items loaned for an exhibition in the 1950s about S&C.) Could we select icons depending on context or it that too complicated? I am also happy to consider using the uncertainty icon exclusively -- it might be better to think about it as the "something's missing" icon.  If there's a public note, there's an uncertainty icon.

2. @clmahoney can confirm, but that issue of _transition_ is a double issue and should simply be "no. 19 – 20, 1930" -- a link to the issue is here, btw: https://gallica.bnf.fr/ark:/12148/bpt6k6436280k.

3. "Read online" sounds right to me.  We will only link to an html page -- you are right about that.  I didn't think it through.

[Skipping numbers -- I have nothing to add.]

6. We are listing first dates of publication.  For translations, we list first date of publication for the specific translation if known, and the first English translation if not.  For multivolume works, we would need to use a range, e.g. Moore's Hail and Farewell would be 1911 – 1914. I like the idea of having two publication dates: one for work and one for edition.  That would require some extra data work, but we could do it.  Having two dates would show when we know the edition and when we don't.  But I also understand if having two dates would be out of scope.

[...]

8. Could we have "Other Creators" or "Other Contributors" after Author, editor, translator, illustrator -- in that order?  Will creators that are also members be hyperlinks?  If so, to where -- member pages?  Author search results?

**Comment by gissoo** [comment] 2020-02-26 16:53
@jkotin @rlskoeser, here are my answers:
1. I think we **do** need an uncertainty icon to communicate all the uncertainty (if they are already recorded in your notes that are intended for the public). 
The "i" icon needs to exist on the site to provide more context (for instance, for the "has card" feature), however I'm providing the option so that it **can**, only if appropriate., to be used on the biography, bibliography, and activities pages (what I mean by "appropriate": for when/if there is a piece of information that we are **sure** and **certain** about, I need to show it in the mock ups to communicate that it is OK for it to exist on these pages, it's up to you to use it at all based on whether you have the appropriate content or not)  – so it can be one icon or the other, or both if the information for each of the two purposes is there. Also, @jkotin the hover text box is my fault, it's not meant to be there anymore, it will link to the bibliography or the biography pages. 

2. When I read "Transition 19-20" in the database and the way it's listed with the volume I thought it is a title variant. Thanks for the info, revising it. 

3. I'm taking @rlskoeser 's suggestion on this. I'm kind of getting lost and becoming unclear about the goals for all the possible links, so I don't think I can propose a good language or organization right now, let's talk about this at the meeting, please. (will add to the agenda)

4. Design-wise I'm ok with italicizing. @rlskoeser I think the line break is still needed for better readability. To me italicizing it doesn't help readability at all, it's mainly for standard/common practices of a "bibliography". I would suggest keeping the line break over italicizing if we can't do both.

5. @jkotin @rlskoeser Thank you for noting this! This is my fault, the designs were not updated, fixed now. (revising)

6. Great input, thank you! Makes a lot of sense. Let's talk about it a bit during our meeting, to make sure I get how it might affect the design. 

7. Yes, sorry again my fault, revising this too. 

8. Worthy to talk about during the meeting as well. (will add to the agenda)

**Comment by gissoo** [comment] 2020-02-26 22:11
@jkotin @rlskoeser @clmahoney @i-davis here are the revisions:

Mobile: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e56ec7c8644f066cb5a4df4)
Tablet: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e56ec376be802745d85c598)
Desktop: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e56ec3788f5977842859060)

**Comment by jkotin** [comment] 2020-02-27 00:24
This all looks great to me.  Some notes:

1. "Read more" should be "Read Online" or "Read/Download" or just "Read"

2. To confirm: if there is no "uncertainty," the public notes would appear where the uncertainty notes are, but without an icon. 

3. Currently there is no publication date for _transition_ on mobile or tablet.

Otherwise, this looks great and I'm ready to close.

**Comment by jkotin** [comment] 2020-02-27 14:24
Excellent. Additional questions that might not exactly be about the design, but come to the fore by looking at the design, @rlskoeser --

1. How will enter dates for a periodical like transition? Will the date of publication (i.e. the date range) be generated by the dates in the editions?

2. On the bibliography page, do we want creator names displayed "last name, first name" -- or would it be easier to read and more accessible if we listed them "first name last name"?  Last name first only makes sense to me when we have alphabetical lists or want to be able to sort alphabetically.

3. Re: "Book" and "Periodical" labels -- will there be other options?  Ideally, we would have a third option, "Other." We can then define the "other" in the public note.

**Comment by jkotin** [comment] 2020-02-27 14:24
Excellent. Additional questions that might not exactly be about the design, but come to the fore by looking at the design, @rlskoeser  --

1. How will enter dates for a periodical like transition? Will the date of publication (i.e. the date range) be generated by the dates in the editions?

2. On the bibliography page, do we want creator names displayed "last name, first name" -- or would it be easier to read and more accessible if we listed them "first name last name"?  Last name first only makes sense to me when we have alphabetical lists or want to be able to sort alphabetically.

3. Re: "Book" and "Periodical" labels -- will there be other options?  Ideally, we would have a third option, "Other." We can then define the "other" in the public note.

**Comment by jkotin** [comment] 2020-02-27 14:27
Excellent. Additional questions that might not exactly be about the design, but come to the fore by looking at the design, @rlskoeser  --

1. How will enter dates for a periodical like transition? Will the date of publication (i.e. the date range) be generated by the dates in the editions?

2. On the bibliography page, do we want creator names displayed "last name, first name" -- or would it be easier to read and more accessible if we listed them "first name last name"?  Last name first only makes sense to me when we have alphabetical lists or want to be able to sort alphabetically.

3. Re: "Book" and "Periodical" labels -- will there be other options?  Ideally, we would have a third option, "Other." We can then define the "other" in the public note.

**Comment by gissoo** [comment] 2020-02-27 14:33
@jkotin I agree with your Q2 for readability purposes. Forgot to ask about this yesterday.

**Comment by rlskoeser** [comment] 2020-02-27 17:51
@jkotin answers by the number
1. I think we previously discussed using dates from the edition record, will that work for both periodical and multivolume items?
2. No strong opinion on name display but a question: when there are multiple names for a single role, should they be sorted by alpha? 
3. Mentioned in slack, the other type currently in the db is "article" but I don't know how useful/accurate that is to you (it came from the OCLC data). Item types are editable, and I think it would be best to display the actual item type rather than "miscellaneous" or "other"

**Comment by gissoo** [comment] 2020-02-27 19:41
@jkotin regarding your Q3, in the designs we had agreed on "books", "periodicals", and "Miscellaneous".
So the third one we had already agreed on, it makes sense to me to explain that in the public notes. @rlskoeser what do you think?

**Comment by jkotin** [comment] 2020-02-27 21:03
In haste: 

1. Sounds good. Yes, it should work.
2. I do think First name last name is best for the bibliography page. The order should reflect the order on the book. Can we follow the order in the database?
3. Great -- yes, let's follow the editable field.  I'll start using it.  There are some photographs.

Can I close?

**Comment by rlskoeser** [comment] 2020-02-28 18:45
It sounds like all the questions have been resolved! It looks to me like we can close it @jkotin

**Closed** 2020-03-02 14:24 UTC
Labels: awaiting review, design

**Comment by gissoo** [comment] 2020-03-02 14:26
The estimate for this issue has changed from 5 to 8 due to the multiple rounds of revisions, uncertainties, and variations in multiple cases with the data.
