### ISSUE TITLE
As a content editor, I want to add and edit purchasing events so that I can add identified purchases visible on lending library cards.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#130] opened 2018-12-04 21:38 UTC
## Testing suggestions:

- [x] In the admin interface, add a purchasing event with account, item from the collection, and required info. It should save and appear in the list view.
- [ ] Try creating an event that is missing one or both required fields. The form should fail to submit.
- [x] Make sure that the expected fields (date, item, account, and currency) are all available.

**Comment by elspethgreen** [comment] 2018-12-18 16:46
For point 2, I'm not sure what this means.  I see inline event-add interfaces for addresses, subscriptions, and reimbursements on the account page, but not purchases.  I'm fine with this--borrows aren't there either--but am I misunderstanding this direction?  Screenshot attached of what I think "inline form in account" means.
![screen shot 2018-12-18 at 10 46 09 am](https://user-images.githubusercontent.com/12616678/50168947-2d5cc700-02b2-11e9-954e-6d89fb565076.png)

**Comment by bwhicks** [comment] 2018-12-18 16:48
@elspethgreen Sorry for the confusion, the direction was in error (it shouldn't be there). I'll remove it.

**Comment by elspethgreen** [comment] 2018-12-18 16:50
@bwhicks Thanks!

**Comment by elspethgreen** [comment] 2018-12-18 16:52
@jkotin I wonder if "price" should actually be a required field.  I don't think I can quickly find an example of a purchase without a price, but I can imagine they might exist.  I also think we should possibly make "Footnotes" required, if only to ensure that the encoders actually remember to use them--I find it the easiest thing to forget to do.  And they really shouldn't be adding something unless they can specify the card on which they found it.

**Comment by bwhicks** [comment] 2018-12-18 17:02
@elspethgreen @jkotin Making `price` optional is easy. Making `footnotes` required I am not sure we can actually do (or if we can do it, it will likely be challenging).

**Comment by elspethgreen** [comment] 2018-12-18 21:10
Per @jkotin's comment on slack/email, let's make price optional and leave the footnotes as they are!

**Comment by bwhicks** [comment] 2018-12-18 21:54
@elspethgreen Great, if you can check this out (and verify that price is now optional), once the issue is to your satisfaction and closed, this will be ready for a release.

**Comment by elspethgreen** [comment] 2018-12-18 22:20
Looks great!  I'll close this out.

**Closed by elspethgreen** 2018-12-18 22:20 UTC
