### ISSUE TITLE
As an admin, I want to generate a data download of member information so that I can deposit and version the data for others to use.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#265] opened 2019-04-10 16:32 UTC
# testing notes
[google drive folder link](https://drive.google.com/drive/folders/1Uu-dememloOoBJGpEjKESBf6wpjMNV7H)

Data is available in both CSV and JSON formats. Please check both. The files are pretty large, and importing in Excel might apply formatting which could be confusing; perhaps OpenRefine would be a good tool to use for opening and reviewing these.

---

Check that all fields below are included, as appropriate for the member. Please also check these specific cases:

- for organizational accounts, the "is organization" value should be set to "true"
- for members with a card, the "has card" value should be set to "true"
- for members with differing names/sort names/titles (e.g. Claude Cahun) the correct information should be listed in each field
- members with gender information should have their gender shown in full-word form (i.e. "Male" instead of "M"); check Cahun in addition to one Female member and one Male member
- for members who have both VIAF and Wikipedia (e.g. Gertrude Stein) they should be the correct URLs and they should be listed separately
- for members with multiple nationalities (e.g. Walter Benjamin), all nationalities should be listed in the data
- for members with no address information, there should be no locations or coordinates shown (and these fields should not appear in the JSON at all)
- for members with an address, the display of the address in the "locations" list should be sufficient to do data work with (i.e. it includes enough information to locate the place)
- for members with multiple addresses, each one should be listed under locations _and_ coordinates _and the order of the two lists should correspond_ (check e.g. Hemingway)

If you know of any other good edge cases, please check those too!

## dev notes
export should include these fields:
- s&co member url
- name
- sort name
- viaf id
- wikipidia url
- birth year
- death year
- is organization
- gender
- title
- nationalities
- locations
- geo coordinates for locations
- public notes
- has card

**Comment by rlskoeser** [comment] 2019-12-12 19:34
Can this include addresses and be used to support data work identifying & documenting relationships between library members?

**Comment by rlskoeser** [comment] 2019-12-16 16:16
Re-estimating to 3pts due to concerns about complex relationships between models that have to be simplified for inclusion in CSV.

**Comment by rlskoeser** [comment] 2020-02-17 21:51
@jkotin I've looked at the models and our data and have a preliminary list of what I suggest we include in the member export.

- s&co member url
- name
- sort name
- viaf id
- wikipidia url
- birth year
- death year
- is organization
- verified
- gender
- title
- nationalities
- locations
- public notes
- has card 

I propose we exclude: 
- profession (I think this is largely unused)
- relationships (also not yet in use, and public display on the website is not MVP)

## Questions
- Addresses include optional dates, care/of person.  I propose that we ignore those and only include addresses for two reasons:  1) I don't think these have been used much yet (the last I checked, no care-of persons had been entered); 2) it's hard to include structured data like this in a CSV
- I am wondering about including a list of years that a member was active. The events export will provide far more details, but it might be nice to have a high-level view of membership in the member export.

**Comment by jkotin** [comment] 2020-02-18 01:38
Excellent.

Questions:

Re: "verified": will including "verified" be useful? I worry that people will think that "unverified" data might be unreliable.  We only attempted to "verify" a small number of tricky cases.

Re: Wikipedia -- unlike with VIAFs, we were very inconsistent about including Wikipedia links.  I think I always thought we'd generate them from the VIAF links.

Answers: I agree about noting including the address dates.  Re: care of -- my sense that that information is important. It shows that the member was staying with an associate -- i.e. didn't have a permanent address in Paris.  Are there really no care of addresses?  Could the care of person have been included in the address?

**Comment by rlskoeser** [comment] 2020-02-18 14:12
Happy to exclude verified from this list. TBH I couldn't remember exactly it meant; it sounds like it won't be that useful.

I see your point about the wikipedia links... I can keep thinking about this (pulling just wikipedia urls from viaf seems simpler than pulling lots of different data from viaf). I'm inclined to include the ones we have, because whenever we add more (by whatever means) they will be included without additional effort.

I know we have addresses that _should_ have care of persons, but I don't think they have been entered. I checked the database again for care of addresses and found that there are now two, but they don't look right to me. **Richardson, Arthur W., Mr.** and **Richardson, Mrs. Arthur W., Mrs** both have addresses associated with their person record rather than their member account, and both addresses have the same name as the care of person. I recommend you have someone clean these up by:
1. Move the addresses from the person record to the corresponding account
2. Remove the care of person name

I checked the XML personography and looked at the locations in the database - the care of names were listed in the xml personography were listed as location names. If you go to the admin list of Locations and search for "c/o" you'll find three and "care of" there is one.  I don't know if there are any other relevant search terms. I recommend you have someone update these.

If you have these updates done, there will still only be a very few people with care of persons in the export — but I'm fine with including them. Any thoughts on how to label the field, do you think "care of" would be sufficient (We'll have accompanying information describing the fields.)

**Comment by jkotin** [comment] 2020-02-18 15:36
@clmahoney would you ask @i-davis to resolve the care of issues (described above) this week?  Would you then check his work and confirm here?

**Comment by i-davis** [comment] 2020-02-18 16:05
@jkotin @clmahoney I'm on it! Will let you know when I've done, Cate!

**Comment by i-davis** [comment] 2020-02-18 16:24
@jkotin @clmahoney

Okay, I finished these issues:

1. I don't know why the Richardsons were like that. I haven't gotten to them yet in the 36 book; their addresses were added through their cards.

2. I should note that once an address is part of a person record, you can't remove it: you get an error message saying that the database won't allow you to leave someone's address blank. You can remove the care of person from the person record, so I did do that. Otherwise, I just added the address to the account as well. Will that make for any problems on your end, @rlskoeser?

3. The care of cases are tricky: for many of them, I had to add the person who is the care of designee to the database. I left notes in their person records that say "ADDP: So-and-so is the care of for one of So-and-so's addresses." I think it makes sense to have added them anyway, right?

Okay, lmk if you have any questions!

**Comment by i-davis** [comment] 2020-02-18 16:42
@jkotin @clmahoney 

Follow-up note: I think "chez So-and-so" functions as the French version of c/o. Right now there are 15 locations that include "chez So-and-so" in the "Name of location" spot. Should we switch those names to the "care of" spot? 

I imagine I'm wrong about this, but for what it's worth, I'd vote no: we'd lose the specificity of knowing that the language the customer and the clerk were speaking was French. (And I mean, technically, "chez So-and-so" _is_ the name of the location, so it's not exactly wrong, right?)

**Comment by jkotin** [comment] 2020-02-18 17:28
I'm not sure how this impacts the structure of the data or the data entry, but when a member has a care of/chez address, I'd like to it show up on the map as:

care of James Joyce
1 rue du Soleil
Paris 8e 

chez Adrienne Monnier
1 rue du Soleil
Paris 8e

When there's no care of/chez, it should show as:

1 rue du Soleil
Paris 8e

**Comment by rlskoeser** [comment] 2020-02-18 18:25
It's fine to leave the chez/care of as the name of the address and also add an associated person to document the care of name in a structured way. I just checked, address names are included in the map on the card (so you _should_ leave them in the name).

@i-davis thanks for cleaning up the addresses. You have to use the 'x' on the right side of the address to remove it from a record.

It makes sense that you'd have to add person records for the care of people. Makes sense to me to have a note! Is ADDP the right code, I thought that was for address book people not in the logbooks?

**Comment by i-davis** [comment] 2020-02-18 18:37
@rlskoeser 

Oh, okay! I'll go put them back in the name of the addresses then. That should mean that the addresses show up in the way Josh designates above, right? (Save for the arr.)

& yes, totally: I was using the x. The problem is that when you click the x, erase the address, and then hit save -- you end up with an error page that says, in a red band at the top: "Please correct the error below." And then if you scroll down to the addresses section, it says in red type below the location field, "This field is required."

As for ADDP, I was using it just a general designator for when I added a person not from the usual sources (cards, logbooks). 36ADDP designates additions from the 1936 address book in particular, so if you search for that you can exclude the non-36 additions.

**Comment by rlskoeser** [comment] 2020-02-18 18:41
@i-davis yes, including the chez/care-of in the location name should result in it displaying the way Josh wants. Easy enough to look at a member page on the public site for someone associated with one of your addresses before and after you make the edit to see.

I think you shouldn't erase the address when you hit the X, but I'm not sure why that would matter. (Maybe it's validating before it hits the remove logic, and it's technically not valid without the required field.) It's not a problem to have the addresses there, I think currently they're ignored. @clmahoney can you confirm if this is a problem and create a bug issue for it if confirmed?

Thanks for explaining the ADDP/36ADDP!

**Comment by rlskoeser** [comment] 2020-02-26 19:55
@jkotin the conversation on this issue went into a tangent about the addresses and data cleanup, and I'm not certain you agreed to the list of fields. I've updated the issue description with the list I propose to include (and added the geographical coordinates explicitly as a separate field, which I think will be desirable for generating maps from this data). Please take a look and let me know if you are ok with this list of fields.

**Comment by jkotin** [comment] 2020-02-26 23:45
This looks perfect to me for members.  Should I close>

**Comment by thatbudakguy** [comment] 2020-03-11 15:21
@clmahoney I added a link to a folder in google drive with copies of the exported data, so I think this is ready for you. let me know if it didn't work.

**Comment by clmahoney** [comment] 2020-03-11 17:34
Testing with CSV file in OpenRefine: 

- YES, I saw that an organizational account (the British Institute) has a TRUE "is organization" value
- YES, all members with cards have a TRUE "has card" value 
- YES, members with differing names and sort names and titles have all correct info listed. Tested Claude Cahun and Princess Bassiano 
- YES, I see gender shown in full-word form: checked Cahun ("Nonbinary"), Roger Caillois ("Male"), and Ruth Camp ("Female")
- YES, members with both VIAF and Wiki links have correct URLS that are separate. I checked Marguerite (Chapin) Caetani / Princess Bassiano.
- YES, members with multiple nationalities, all nationalities are listed. I checked Emma Goldman: "France;Lithuania;United Kingdom;United States;[no country]"
- YES, members with no address information do not have locations or coordinates shown 
- YES, if a member has a listed address then the display of the address in the "locations" list should be sufficient to do data work with. I checked Mme Léon Gischia (7 rue de l'Estrapade, Paris and coordinates)
- YES, members with multiple addresses have those addresses listed under locations and coordinates and the order of the two lists corresponds. I checked Grassot, Mme R. who has two.

**Comment by clmahoney** [comment] 2020-03-11 17:56
Testing JSON in OpenRefine: 

- YES, organizational accounts has a "true""is organization" value - checked British Institute 
- YES, all members with cards have a TRUE "has card" value
- YES, members with differing names and sort names and titles have all correct info listed. Tested 
Helen (Green) Baldwin / Mrs. James Mark Baldwin.
- YES, I see gender shown in full-word form: checked Cahun ("Nonbinary"), Mrs. Thornton Baker ("Female"), and Arthur C. J. Baldwin ("Male")
- YES, members with both VIAF and Wiki links have correct URLS that are separate. I checked Walter Benjamin. 
- YES, members with multiple nationalities, all nationalities are listed. **BUT** it seems to move the other nationality to another row: See this example with Benjamin: 
![Screen Shot 2020-03-11 at 1 49 39 PM](https://user-images.githubusercontent.com/16673934/76447682-75787580-639f-11ea-88f7-7b8a4bab00bd.png). Is that a problem? 
- YES, I see coordinates and addresses only with members who have them. I still see these fields in JSON in OpenRefine though: 
![Screen Shot 2020-03-11 at 1 53 29 PM](https://user-images.githubusercontent.com/16673934/76447828-b96b7a80-639f-11ea-91c7-fec2f6a0f71a.png)
- YES, if a member has a listed address then the display of the address in the "locations" list should be sufficient to do data work with. I checked Louise Bennett. 
- YES, members with multiple addresses have those addresses listed under locations and coordinates and the order of the two lists corresponds. I checked Agnes Claudius, again multiple boxes appear: 
![Screen Shot 2020-03-11 at 1 55 54 PM](https://user-images.githubusercontent.com/16673934/76448028-15ce9a00-63a0-11ea-8a15-b6dbde02a841.png)

**Comment by thatbudakguy** [comment] 2020-03-11 18:37
@clmahoney I think this behavior in OpenRefine is correct; it knows that those multi-valued fields correspond to a single person and is showing you them accordingly. It has to show the column since some members have it, but if you look in the actually JSON file the fields shouldn't be there.

thanks for the thorough testing on this! I think you can go ahead and close it.

**Closed** 2020-03-11 18:45 UTC
Labels: question
