### ISSUE TITLE
Design to communicate the absence of a card image when it is not loading 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#548] opened 2020-03-30 15:53 UTC

**Comment by gissoo** [comment] 2020-04-06 21:25
Here is the design for this issue, please let me know what you think.
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e8b988806ea3db826006fce)

**Comment by jkotin** [comment] 2020-04-07 00:55
These looks great and I'm happy to approve. My questions: 1/ is the faint graph paper background is necessary? 2/ Do we need any kind of error message to make the problem explicit? I defer to @gissoo on both these questions. @rlskoeser how common will not loading be?

**Comment by rlskoeser** [comment] 2020-04-07 13:59
@jkotin I discussed with @gissoo and recommended we not put any error messages are wording, because we won't necessarily know what the problem is when an image doesn't load.

The simplest way to implement this is to use the image Gissoo has created as a placeholder image, so you'll see it if images are slow to load or if they don't load at all. The scenarios I can think of where an image won't load at all are:
- Something is wrong with the Figgy manifest and our information is out date (e.g., edits have been made but we haven't pulled them in yet); this is under our control and I expect to be resolved before May
- the PUL image server is temporarily unavailable (I don't expect this to happen often or to last long when it does)

**Comment by jkotin** [comment] 2020-04-07 14:03
@rlskoeser Sounds good.

In the rare case in which the images don't load, is there a way for us to know? Or would we have to discover the problem ourselves or have a user contact us?

I'm happy to close this when @gissoo responds.

**Comment by gissoo** [comment] 2020-04-07 14:13
@jkotin @rlskoeser  Thanks for writing. I think the graph paper is helping the icon, it would look too plain without it. I had rather keep it as is. 

@jkotin Regarding the question you asked in your latest comment, I would defer to @rlskoeser as I'm not sure the exact flow of finding out something is wrong. But I think it's always good if users can report to us if they notice that something is wrong, which is possible through "Contact Us" that we have.

**Comment by rlskoeser** [comment] 2020-04-07 14:15
@jkotin I'm not sure how we'd know if an image isn't loading. I can think about what kind of automated reporting or scanning we could set up to check this for us, or see if PUL has any tools that would help with this.

**Comment by jkotin** [comment] 2020-04-07 14:49
This all sounds good to me.  It would be great to have some way of being alerted if a card loading problem lasts for a longer period of time.

**Closed by jkotin** 2020-04-07 14:49 UTC
Labels: awaiting review, design
