### ISSUE TITLE
add info links in interface

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#456] opened 2019-12-02 15:44 UTC
# testing notes
## designs
member search - [desktop](https://zpl.io/bJpxmnr) / [tablet](https://zpl.io/VDABKWq) / [mobile](https://zpl.io/aRz0A9E)
membership activities - [desktop](https://zpl.io/bP98J9D) / [tablet](https://zpl.io/aBKXODm) / [mobile](https://zpl.io/adX5gYe)
## checklist
this issue is for design testing the new "info link" icon/functionality, which will link pages on the site to particular sections on another page (likely the FAQ page). note that the links themselves will not actually go to the right place yet, because the FAQ page and its sections do not yet exist (that's issue #464).

to test it, check the two locations that used to be tooltips, but are now info links:
- next to the gender facet, on members search
- next to the "plan" column on membership activities table

confirm that the info links show up in the correct places on all screens - mobile especially is important because they get moved around, e.g. on borrowing activities the link moves to the first card in the list.

**Comment by thatbudakguy** [comment] 2019-12-05 17:57
@rlskoeser is this now a duplicate of #464?

**Comment by clmahoney** [comment] 2019-12-11 18:45
Desktop 
- YES, I can see the link button near the gender facet under demographics on the main member page. If I click it, right now it takes me to an "absent on business" page which will soon be gender-essay-filled. I see the URL is faq/#why-assign-gender. 
- YES, I can see the link button near the plan facet on the individual member activity page (I checked Pauline Alderman). If I click it, it brings me to another "absent on business page" but I see the URL is /faq/#joining-the-library - so that will be where the plan info is.

**Comment by clmahoney** [comment] 2019-12-11 19:03
Mobile: 
- YES, I can see the link button to the right of the gender. I am able to click it and it brings me to a new page (with an "absent on business" message) See screenshot! 
![Image from iOS (8)](https://user-images.githubusercontent.com/16673934/70651012-1aa77480-1c1e-11ea-96ea-4217a6177091.png)

- YES, I can see the link button near the plan facet on the individual member activity page: I checked Alvear this time. I'm able to click the link and it brings me to a new page that brings me to the FAQ URL.

**Comment by clmahoney** [comment] 2019-12-12 01:51
Tablet: 
- YES, I can see the link button to the right of the gender. I am able to click it and it brings me to the new FAQ page. 
- YES, I can see the link button near the plan facet on the individual member activity page (I checked Pauline Alderman again). If I click it, it now brings me to the new FAQ page.

**Comment by jkotin** [comment] 2019-12-12 14:25
This looks good. Seeing it on the test site, I have a few suggestions re: language. If these suggestions can't be adopted or if they are misguided, let me know!

1. Change "FAQ" to "Frequently Asked Questions"
2. Change "Why do we identify gender?" to "Why do we identify the gender of lending library members?"
3. Change "Why do we identify nationality?" to "Why do we identify than nationality of lending library members?"

**Comment by rlskoeser** [comment] 2019-12-12 14:48
Updated the info links to use the new target urls and text we came up with, and to add nationality. I also added a provisional style (which I discussed with Gissoo) to highlight the section within the FAQ that you linked to.

**Comment by rlskoeser** [comment] 2019-12-12 14:52
@jkotin those language changes are fine with me, but it does make me think we should make the anchor link independent of the title, so it can be shorter and more stable. I'm going to re-open #464 so we can revise and retest.

**Comment by jkotin** [comment] 2019-12-12 14:53
Sounds good.

**Comment by rlskoeser** [comment] 2019-12-12 15:37
Have revised the link targets and updated FAQ on test accordingly. Please check that all info links display and resolve correctly. Please also check nationality info link on mobile, since that was added since the previous testing.

**Comment by clmahoney** [comment] 2019-12-12 21:54
Desktop: 
- YES, when I click the gender link it takes me to the FAQ page, and the "FAQ" page now reads "Frequently Asked Questions" at the top
- YES, when I click on the nationality link it takes me to the FAQ page, to the URL faq/#lending-library-plans

**Comment by clmahoney** [comment] 2019-12-12 21:59
Mobile: 
- YES, when I click the gender link it takes me to the new "Frequently Asked Questions" page
- YES, the nationality link works and takes me to the new "Frequently Asked Questions" page
see screenshot for the nationality link on mobile: 
![Image from iOS (11)](https://user-images.githubusercontent.com/16673934/70752459-aa255400-1d00-11ea-9a7c-1913b73e7570.png)

**Comment by clmahoney** [comment] 2019-12-12 22:02
Tablet: 
- YES, gender link works! Takes me to FAQ! 
- YES, nationality link works! Also takes me to FAQ!

**Comment by clmahoney** [comment] 2019-12-12 22:02
Also all the language that @jkotin wanted updated has been updated. Can I close?

**Closed** 2019-12-12 22:07 UTC
Labels: awaiting design testing
