### ISSUE TITLE
VIAF and Dates

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#31] opened 2017-08-17 02:27 UTC
Its seems that VIAF and birth and death dates can override one another. If I enter a VIAF number and save, and then enter random birth and death dates, the VIAF disappears. If I enter birth and death dates and save, and then enter a random VIAF, the birth and death dates disappear. This is a problem because some of the dates in VIAF are incorrect, but we still want to retain the VIAF link.

**Comment by rlskoeser** [comment] 2017-08-17 15:06
I think this is really a duplicate of #29, but I'm going to leave it open because I would like you to confirm that the VIAF + date behavior is workable.

Right now, if you add a VIAF id it will populate the birth and death dates from the VIAF record.  (This can actually happen two different ways: when you pick an item from the autocomplete _or_ if you save a record with a VIAF id but no dates, the backend code will try to look up the dates and set them.  This is a result of the change to support searching on VIAF number, because previously the birth and death dates weren't available in the autocomplete data.)

This behavior _only_ happens when you change the VIAF id using the autocomplete.  So if you associate a person with a VIAF id and then correct the dates, they will not be changed (unless you do the VIAF lookup again).

As we discussed before, for the import script #14, any dates in the xml will be used - the VIAF lookup is only used when a person has a VIAF id but no birth/death dates.

**Comment by bwhicks** [comment] 2017-10-11 18:15
I checked with @elspethgreen and she thought this was fine at the meeting, but she will check in with @jkotin that this functionality is OK.

**Comment by elspethgreen** [comment] 2017-10-11 21:17
Checked with Josh, he says it's okay!

**Closed** 2017-10-11 21:18 UTC
